version: '3'

services:
  db:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER:-importer}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-importer}

  web:
    build: .
    environment: &web_env
      - DJANGO_SETTINGS_MODULE=importer.conf.docker
      - SECRET_KEY=${SECRET_KEY:-vn#(34r7koa^sq1=w+m13gtrps)wz35kt1v72j%s4lb32d25u3f}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_LOGLEVEL=DEBUG
    ports:
      - 8000:8000
    volumes:
      - media:/app/media
      - private_media:/app/private_media
    depends_on:
      - db
      - redis

  redis:
    # NOTE: No persistance storage configured.
    # See: https://hub.docker.com/_/redis/
    image: redis:5
    ports:
      - 6379:6379

  celery:
    build: .
    environment: *web_env
    command: /celery_worker.sh
    volumes:
      - media:/app/media
      - private_media:/app/private_media
    depends_on:
      - db
      - redis

volumes:
  media:
  private_media:
