# Generated by Django 2.2.17 on 2021-02-08 15:14

from django.db import migrations


def clear_catalogs(apps, schema_editor):
    """
    we're very early in the project so let's just delete dev data instead of trying to upgrade it
    """
    Job = apps.get_model("core", "Job")
    Catalog = apps.get_model("core", "CatalogConfig")
    Job.objects.all().delete()
    Catalog.objects.all().delete()


def ensure_zgw_service(apps, schema_editor):
    """
    we want to add a non-nullable field to existing model so make sure we always have a record for the one-time default
    """
    Service = apps.get_model("zgw_consumers", "Service")
    if not Service.objects.filter(id=1).exists():
        Service.objects.create(id=1, label="Dummy Placeholder")


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("core", "0005_statistics_field"),
    ]

    operations = [
        migrations.RunPython(clear_catalogs, clear_catalogs),
        migrations.RunPython(ensure_zgw_service, migrations.RunPython.noop),
    ]
