# Generated by Django 2.2.17 on 2021-02-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("core", "0006_catalogconfig_uuid_prepare"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogconfig",
            name="url",
        ),
        migrations.AddField(
            model_name="catalogconfig",
            name="service",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"api_type": "ztc"},
                on_delete=django.db.models.deletion.PROTECT,
                to="zgw_consumers.Service",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="catalogconfig",
            name="uuid",
            field=models.UUIDField(
                default="7b3ffaf1-c4a6-4dec-a08b-1f1b4acb4a49",
                help_text="Unieke resource identifier (UUID4)",
                verbose_name="UUID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="catalogconfig",
            name="label",
            field=models.CharField(
                help_text="Human readable label.", max_length=255, verbose_name="Label"
            ),
        ),
    ]
