# Generated by Django 2.2.17 on 2021-03-01 14:26

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_catalogconfig_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="close_published",
            field=models.BooleanField(
                default=False,
                help_text="Close existing records on Start date",
                verbose_name="Close published records",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="start_date",
            field=models.DateField(
                default=datetime.date.today,
                help_text="Optional set start date of new records. Defaults to today.",
                verbose_name="Start date",
            ),
        ),
    ]
