# Generated by Django 2.2.13 on 2020-08-05 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0010_nlxconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="SelectielijstConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        limit_choices_to={"api_type": "orc"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="zgw_consumers.Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Selectielijst configuration",
            },
        ),
    ]
