name: quick-start

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Download docker-compose file
        run: wget https://raw.githubusercontent.com/maykinmedia/catalogi-importer/master/docker-compose-quickstart.yml -O docker-compose-qs.yml
      - name: Start docker containers
        run: docker-compose -f docker-compose-qs.yml up -d
      - name: Wait until DB container starts
        run: sleep 10
      - name: Load fixtures
        run: docker-compose -f docker-compose-qs.yml exec -T web src/manage.py loaddata demodata
      - name: Check main page
        run: |
          curl_status=$(curl -w '%{http_code}' -o /dev/null  -s http://localhost:8000/)
          if [[ $curl_status != 200 ]]; then
            printf "index page responds with %curl_status status" >&2
            exit 1
          fi
